// 語別對照表（languages 表 seed）。來源：klokah dialectView.xml（權威 name_zh）。
// 欄位: { lang_code, dialect_id, name_zh, name_native, active }
// dialectId 33（太魯閣語）lang_code 固定 'trv'，對齊 vocabulary.lang_code DEFAULT。
// active=1 代表上架可選；預設全部語別 active=1（詞庫 seed 皆已備妥）。
module.exports = [
  { lang_code: "ami-nanshi", dialect_id: 1, name_zh: "南勢阿美語", name_native: "Pangcah", active: 1 },
  { lang_code: "ami-siwkolan", dialect_id: 2, name_zh: "秀姑巒阿美語", name_native: "Pangcah", active: 1 },
  { lang_code: "ami-coastal", dialect_id: 3, name_zh: "海岸阿美語", name_native: "Pangcah", active: 1 },
  { lang_code: "ami-malan", dialect_id: 4, name_zh: "馬蘭阿美語", name_native: "Pangcah", active: 1 },
  { lang_code: "ami-hengchun", dialect_id: 5, name_zh: "恆春阿美語", name_native: "Pangcah", active: 1 },
  { lang_code: "tay-squliq", dialect_id: 6, name_zh: "賽考利克泰雅語", name_native: "Tayal", active: 1 },
  { lang_code: "tay-culi", dialect_id: 7, name_zh: "澤敖利泰雅語", name_native: "Tayal", active: 1 },
  { lang_code: "tay-mnawyan", dialect_id: 8, name_zh: "汶水泰雅語", name_native: "Tayal", active: 1 },
  { lang_code: "tay-mabtalah", dialect_id: 9, name_zh: "萬大泰雅語", name_native: "Tayal", active: 1 },
  { lang_code: "tay-skikun", dialect_id: 10, name_zh: "四季泰雅語", name_native: "Tayal", active: 1 },
  { lang_code: "tay-yilan-culi", dialect_id: 11, name_zh: "宜蘭澤敖利泰雅語", name_native: "Tayal", active: 1 },
  { lang_code: "xsy", dialect_id: 13, name_zh: "賽夏語", name_native: "SaySiyat", active: 1 },
  { lang_code: "ssf", dialect_id: 14, name_zh: "邵語", name_native: "Thao", active: 1 },
  { lang_code: "sdq-tgdaya", dialect_id: 15, name_zh: "都達語", name_native: "Seediq", active: 1 },
  { lang_code: "sdq-tkdaya", dialect_id: 16, name_zh: "德固達雅語", name_native: "Seediq", active: 1 },
  { lang_code: "sdq-truku", dialect_id: 17, name_zh: "德鹿谷語", name_native: "Seediq", active: 1 },
  { lang_code: "bnn-takituduh", dialect_id: 18, name_zh: "卓群布農語", name_native: "Bunun", active: 1 },
  { lang_code: "bnn-takbanuaz", dialect_id: 19, name_zh: "卡群布農語", name_native: "Bunun", active: 1 },
  { lang_code: "bnn-takivatan", dialect_id: 20, name_zh: "丹群布農語", name_native: "Bunun", active: 1 },
  { lang_code: "bnn-takitakbanuad", dialect_id: 21, name_zh: "巒群布農語", name_native: "Bunun", active: 1 },
  { lang_code: "bnn-isbukun", dialect_id: 22, name_zh: "郡群布農語", name_native: "Bunun", active: 1 },
  { lang_code: "pwn-east", dialect_id: 23, name_zh: "東排灣語", name_native: "Paiwan", active: 1 },
  { lang_code: "pwn-north", dialect_id: 24, name_zh: "北排灣語", name_native: "Paiwan", active: 1 },
  { lang_code: "pwn-central", dialect_id: 25, name_zh: "中排灣語", name_native: "Paiwan", active: 1 },
  { lang_code: "pwn-south", dialect_id: 26, name_zh: "南排灣語", name_native: "Paiwan", active: 1 },
  { lang_code: "dru-budai", dialect_id: 27, name_zh: "東魯凱語", name_native: "Drekay", active: 1 },
  { lang_code: "dru-wutai", dialect_id: 28, name_zh: "霧台魯凱語", name_native: "Drekay", active: 1 },
  { lang_code: "dru-tanan", dialect_id: 29, name_zh: "大武魯凱語", name_native: "Drekay", active: 1 },
  { lang_code: "dru-teldreka", dialect_id: 30, name_zh: "多納魯凱語", name_native: "Drekay", active: 1 },
  { lang_code: "dru-maga", dialect_id: 31, name_zh: "茂林魯凱語", name_native: "Drekay", active: 1 },
  { lang_code: "dru-mantauran", dialect_id: 32, name_zh: "萬山魯凱語", name_native: "Drekay", active: 1 },
  { lang_code: "trv", dialect_id: 33, name_zh: "太魯閣語", name_native: "Truku", active: 1 },
  { lang_code: "ckv", dialect_id: 34, name_zh: "噶瑪蘭語", name_native: "Kavalan", active: 1 },
  { lang_code: "tsu", dialect_id: 35, name_zh: "鄒語", name_native: "Cou", active: 1 },
  { lang_code: "xnb", dialect_id: 36, name_zh: "卡那卡那富語", name_native: "Kanakanavu", active: 1 },
  { lang_code: "sxr", dialect_id: 37, name_zh: "拉阿魯哇語", name_native: "Hlaʼalua", active: 1 },
  { lang_code: "pyu-nanwang", dialect_id: 38, name_zh: "南王卑南語", name_native: "Pinuyumayan", active: 1 },
  { lang_code: "pyu-katratripul", dialect_id: 39, name_zh: "知本卑南語", name_native: "Pinuyumayan", active: 1 },
  { lang_code: "pyu-west", dialect_id: 40, name_zh: "西群卑南語", name_native: "Pinuyumayan", active: 1 },
  { lang_code: "pyu-jianhe", dialect_id: 41, name_zh: "建和卑南語", name_native: "Pinuyumayan", active: 1 },
  { lang_code: "tao", dialect_id: 42, name_zh: "雅美語", name_native: "Tao", active: 1 },
  { lang_code: "szy", dialect_id: 43, name_zh: "撒奇萊雅語", name_native: "Sakizaya", active: 1 },
];
